title: Teach Yourself LLM
theme: minima
markdown: kramdown

# Optional: Show pages as nav links
navigation:
  - title: Home
    url: /
  - title: Weekly Plan
    url: /plan
  - title: About
    url: /about
  - title: Crash Course
    url: /crash_course
